name: periscope_2022
channels:
- conda-forge
dependencies:
- conda-forge::python=3.9.15
- conda-forge::pandas=1.5.2
- conda-forge::numpy=1.23.5
- conda-forge::jupyter
- conda-forge::jupyterlab
- conda-forge::ipykernel=6.19.2
- conda-forge::matplotlib=3.6.2
- conda-forge::seaborn=0.12.1
- conda-forge::umap-learn=0.5.3
- conda-forge::hdbscan=0.8.29
- conda-forge::joblib=1.2.0
- conda-forge::scikit-image=0.19.3
- conda-forge::imageio=2.22.4
- conda-forge::scipy==1.8.0
- conda-forge::venn==0.1.3
- conda-forge::goatools
- conda-forge::wget 
- conda-forge::boto3==1.26.152
- pip
- pip:
  - git+https://github.com/cytomining/pycytominer@ea9873ddd3b7d9b7072cf7fc55d582012cf6d315
  - cytominer_eval==0.1
  - gseapy==1.0.3
