name: periscope_2022
channels:
- conda-forge
dependencies:
- conda-forge::python=3.7.1
- conda-forge::pandas=1.2.0
- conda-forge::numpy
- conda-forge::pathlib
- conda-forge::jupyter
- conda-forge::jupyterlab
- conda-forge::ipykernel=5.1.0
- conda-forge::nb_conda_kernels=2.2.1
- conda-forge::widgetsnbextension=3.5.1
- conda-forge::jupyter_contrib_nbextensions=0.5.1
- conda-forge::matplotlib
- conda-forge::plotnine
- conda-forge::adjusttext
- conda-forge::seaborn
- conda-forge::black
- conda-forge::dvc-s3
- conda-forge::umap-learn
- conda-forge::hdbscan
- conda-forge::joblib==1.1.0
- pip
- pip:
  - git+https://github.com/cytomining/pycytominer@fdd0e0935ab5446f5c3710e5270c5234d8ef18f1
  - cytominer_eval==0.1
